language: node_js
node_js:
  - "6.10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
install:
  - npm install -g codecov
  - npm install --no-optional
cache:
  directories:
    - node_modules
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --timeout 15000 
  - codecov
