language: node_js
node_js:
  - "12.4.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
install:
  - npm install -g codecov
  - npm install --no-optional
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test-cover 
  - codecov
